### ISSUE TITLE
Webbrowser

### ISSUE THREAD

**Issue by schriftgestalt** [graphicore/Atem-MOM-Glyphs-Integration#1]
> For the planned interaction no dependency to the DOM is required. Can we have a direct JavaScript-Cocoa binding without a web browser in between? This should greatly reduce the startup time, because browsers are heavy.

The plugin would use one instance of a webkit view. It’s not that heavy (it was used on early iOS on all places where you needed styled text). It can keep the instance around so I don't think there will be an performance issue.

**Comment by graphicore** [comment]
OK, maybe you're right.
